sudo: required
services:
  - docker
script:
  - docker build -t swaldiecodes/node .
  - docker images swaldiecodes/node

before_deploy:
  - docker login -u swaldiecodes -p 724ALEN55ezW@B/

deploy:
  provider: script
  script: docker push swaldiecodes/node
  on:
    branch: master
